name:  test

on:
  push:

jobs:
  test:
     runs-on: ubuntu-latest
     steps:
     - name: Setup bazel
       uses: jwlawson/actions-setup-bazel@v1.0
       with:
        bazel-version: '3.3.0'
     - name: Check out code into the Go module directory
       uses: actions/checkout@v2
     - name: start
       run: bazel run //:gazelle
     - name: build
       run: bazel build //cmd/test:test